# FROM node:22.9-alpine

# WORKDIR /app

# COPY package.init.cjs package.json tsconfig.json tsconfig.build.json nest-cli.json jest.config.json ./
# COPY src ./src
# COPY test ./test
# COPY doc ./doc

# RUN node package.init.cjs && npm install && npm cache clean --force && npm run build

# CMD npm run start:dev

# COMPACT VARIANT (439 Mb):
# ------------------------------------------------
FROM node:22.9-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY src ./src
COPY tsconfig.json tsconfig.build.json ./
RUN npm run build

FROM node:22.9-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --frozen-lockfile

COPY --from=build /app/dist ./dist
COPY doc ./doc
COPY docker/app/init.sh ./

RUN chmod +x ./init.sh

CMD ["sh", "init.sh"]