FROM node:22.9-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY src ./src
COPY tsconfig.json tsconfig.build.json ./
RUN npm run build

FROM node:22.9-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --frozen-lockfile

COPY --from=build /app/dist ./dist
COPY doc ./doc
CMD ["node", "dist/main.js"]
