FROM postgres:17.1-alpine

WORKDIR /docker-entrypoint-initdb.d

# RUN apt-get update && apt-get install -y locales \
#     && locale-gen en_US.UTF-8 \
#     && update-locale LANG=en_US.UTF-8

# RUN apk add --no-cache --update musl musl-utils musl-locales tzdata

# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8

COPY init.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init.sh

CMD ["postgres"]
