#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$DATABASE_HOST" --dbname "$DATABASE_HOST" <<-EOSQL
    CREATE USER "$DATABASE_USER" WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE "$DATABASE_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USER";

    \c "$DATABASE_NAME" "$DATABASE_USER"

    CREATE SCHEMA "$DATABASE_SCHEMA";
    GRANT USAGE, CREATE ON SCHEMA "$DATABASE_SCHEMA" TO "$DATABASE_USER";
    ALTER SCHEMA "$DATABASE_SCHEMA" OWNER TO "$DATABASE_USER";

    SET search_path TO "$DATABASE_SCHEMA";
EOSQL