services:
  app:
    #image: sunsundr/home-library-service-app:dev-latest
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    container_name: ${CONTAINER_NAME_APP}
    env_file: .env
    environment:
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_CONTAINER_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_DROPSCHEMA: ${TYPEORM_DROPSCHEMA}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      CRYPT_SALT: ${CRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      LOG_FILE_MAX_SIZE_KB: ${LOG_FILE_MAX_SIZE_KB}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_VERBOSE_STACK: ${LOG_VERBOSE_STACK}
      # ENV_LOADED: ${ENV_LOADED}
      ORM_TYPE: ${ORM_TYPE}
    restart: on-failure
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
    # stop_signal: SIGINT
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./doc:/app/doc
      - /app/node_modules
      # - app-data:/app/data
      - app-data:/app/dist/typeorm/migrations
    depends_on:
      - postgres
    networks:
      - custom_bridge_network

  postgres:
    # image: sunsundr/home-library-service-postgres:dev-latest
    build:
      context: ./docker/postgres
      dockerfile: dockerfile
    container_name: ${CONTAINER_NAME_DB}
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # DATABASE_USER: ${DATABASE_USER}
      # DATABASE_NAME: ${DATABASE_NAME}
      # DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      # DATABASE_HOST: ${DATABASE_CONTAINER_HOST}
      # POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_PORT}:${DATABASE_PORT}"
    volumes:
      #- ./src/typeorm/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    #command: ["bash", "-c", "chmod +x /docker-entrypoint-initdb.d/init.sh && docker-entrypoint.sh postgres"]
    networks:
      - custom_bridge_network

volumes:
  postgres-data:
  postgres-logs:
  app-data:

networks:
  custom_bridge_network:
    driver: bridge