services:
  app:
    image: sunsundr/home-library-service-app:prod-final
    container_name: ${CONTAINER_NAME_APP}
    env_file: .env
    environment:
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_CONTAINER_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_DROPSCHEMA: ${TYPEORM_DROPSCHEMA}
      ORM_LOGGING: ${ORM_LOGGING}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      CRYPT_SALT: ${CRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      LOG_FILE_MAX_SIZE_KB: ${LOG_FILE_MAX_SIZE_KB}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_VERBOSE_STACK: ${LOG_VERBOSE_STACK}
      ORM_TYPE: ${ORM_TYPE}
      SWAGGER_USE_STATIC_SCHEMA: ${SWAGGER_USE_STATIC_SCHEMA}
    restart: on-failure
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - startup:/app/startup
      - app-logs:/app/logs
      - prisma-migrations:/app/src/prisma/migrations
      - typeorm-migrations:/app/src/typeorm/migrations
      - /app/dist/typeorm/migrations # Anonymous volume for compiled files
    depends_on:
      - postgres
    networks:
      - custom_bridge_network

  postgres:
    image: sunsundr/home-library-service-postgres:prod-final
    container_name: ${CONTAINER_NAME_DB}
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - custom_bridge_network

volumes:
  postgres-data:
  postgres-logs:
  typeorm-migrations:
  prisma-migrations:
  startup:
  app-logs:

networks:
  custom_bridge_network:
    driver: bridge