services:
  app:
    image: sunsundr/home-library-service-app:dev-latest
    environment:
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_CONTAINER_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_DROPSCHEMA: ${TYPEORM_DROPSCHEMA}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
    container_name: ${CONTAINER_NAME_APP}
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - custom_bridge_network

  postgres:
    image: sunsundr/home-library-service-postgres:dev-latest
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_HOST: ${DATABASE_CONTAINER_HOST}
    ports:
      - "${POSTGRES_PORT}:${DATABASE_PORT}"
    volumes:
      #- ./src/typeorm/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    #command: ["bash", "-c", "chmod +x /docker-entrypoint-initdb.d/init.sh && docker-entrypoint.sh postgres"]
    networks:
      - custom_bridge_network

volumes:
  postgres-data:
  postgres-logs:

networks:
  custom_bridge_network:
    driver: bridge